---
- name: list directory
  find:
    paths: '{{ item.dir }}'
    recurse: no
    file_type: directory
    excludes: '{{item.dir_excl | default("")}}'
  register: paths
- set_fact:
    new_item: "{{ item | combine({ 'type': 'multi', 'srcs': paths.files|map(attribute='path') }) }}"
- update_fact:
    item: '{{ new_item }}'
- name: write backup script
  template:
    src: restic_script_multi_Linux.j2
    dest: "{{ restic_script_dir }}/backup-{{ item.name | replace(' ', '') }}.sh"
    mode: '0700'
    owner: '{{ restic_dir_owner }}'
    group: '{{ restic_dir_group }}'
